version: "3.5"
services:
  rabbit:
    image: rabbitmq:latest
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  temperature_server:
    build: ../temperatureServer
    volumes:
       - ../temperatureServer:/code
    depends_on:
      - postgres
      - rabbit
  humidity_server:
    build: ../humidityServer
    volumes:
       - ../humidityServer:/code
    depends_on:
      - postgres
      - rabbit
  ph_server:
    build: ../phServer
    volumes:
       - ../phServer:/code
    depends_on:
      - postgres
      - rabbit
  simulators:
    build: ../simulators
    volumes:
       - ../simulators:/code
    depends_on:
      - postgres
      - rabbit
  webapp:
    build: ../webApp
    environment:
      - NODE_PATH = ./webApp/src
    ports:
      - "3000:3000"
    volumes:
      - ../webApp:/code
      - /code/node_modules
  webservice:
    build: ../webService
    volumes: 
      - ../webService:/code
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=server.py
      - FLASK_DEBUG=1
