version: "3.5"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ../webService/config/:/etc/nginx/conf.d
      - ../webService/uploads/:/code/pictures
    ports:
      - 8000:80
  rabbit:
    image: rabbitmq:latest
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  temperature_server:
    image: amoedo/temperature_server
    build: ../temperatureServer
    env_file:
      - .env
    volumes:
       - ../temperatureServer:/code
    depends_on:
      - postgres
      - rabbit
  humidity_server:
    image: amoedo/humidity_server
    build: ../humidityServer
    env_file:
      - .env
    volumes:
       - ../humidityServer:/code
    depends_on:
      - postgres
      - rabbit
  ph_server:
    image: amoedo/ph_server
    build: ../phServer
    env_file:
      - .env
    volumes:
       - ../phServer:/code
    depends_on:
      - postgres
      - rabbit
  ilumination_server:
    image: amoedo/ilumination_server
    build: ../iluminationServer
    env_file:
      - .env
    volumes:
       - ../iluminationServer:/code
    depends_on:
      - postgres
      - rabbit
  water_level_server:
    image: amoedo/water_level_server
    build: ../waterLevelServer
    env_file:
      - .env
    volumes:
       - ../waterLevelServer:/code
    depends_on:
      - postgres
      - rabbit
  water_temperature_server:
    image: amoedo/water_temperature_server
    build: ../waterTemperatureServer
    env_file:
      - .env
    volumes:
       - ../waterTemperatureServer:/code
    depends_on:
      - postgres
      - rabbit
  drawer_status_server:
    image: amoedo/drawer_status_server
    build: ../drawerStatusServer
    env_file:
      - .env
    volumes:
       - ../drawerStatusServer:/code
    depends_on:
      - postgres
      - rabbit
  image_server:
    image: amoedo/image_server
    build: ../imageServer
    env_file:
      - .env
    volumes:
       - ../imageServer:/code
    depends_on:
      - postgres
      - rabbit
  simulators:
    build: ../simulators
    env_file:
      - .env
    volumes:
       - ../simulators:/code
    depends_on:
      - postgres
      - rabbit
  webapp:
    build: ../webApp
    env_file:
      - .env
    environment:
      - NODE_PATH = ./webApp/src
    ports:
      - "3000:3000"
    volumes:
      - ../webApp:/code
      - /code/node_modules
  webservice:
    build: ../webService
    env_file:
      - .env
    volumes: 
      - ../webService:/code
    environment:
      - FLASK_APP=server.py
      - FLASK_DEBUG=1
